### ISSUE TITLE
how to create word document with bullets in it

### ISSUE THREAD

**Issue by rdevagiri-shell** [unidoc/unioffice-examples#17]
Hi,
 I am facing an issue to create a word document with bullet points in it. Can you please help on this issue. 

Attached the reference link for that.

Thanks,
<img width="462" alt="Screenshot 2021-09-27 at 1 35 19 PM" src="https://user-images.githubusercontent.com/78723758/134868799-c162ac19-5ec1-4e36-be8a-452768f821cc.png">

Ravi

**Comment by rdevagiri-shell** [comment]
Does it support numbering bullets?, like

1. First One
2. Second One
3. Third One
4. Fourth One
5. Fivth One

**Comment by sampila** [comment]
Hi @rdevagiri-shell,
About bullet and numbering, you can see this example https://github.com/unidoc/unioffice-examples/tree/master/document/bullet-and-numbering

**Comment by jilieryuyi** [comment]
> Hi @rdevagiri-shell, About bullet and numbering, you can see this example https://github.com/unidoc/unioffice-examples/tree/master/document/bullet-and-numbering

This example cannot be read numbering correctly
got：
https://
1
https://
2
1. https://
3
https://
4
美女
111
 Aaa
 Bbb
 ccc
22

render like this:
![1](https://user-images.githubusercontent.com/2398119/195065526-ee916691-3b3d-43da-bb32-ffc80f60ac0f.png)



simple file for test：

[HYPERLINK.docx](https://github.com/unidoc/unioffice-examples/files/9754086/HYPERLINK.docx)

**Comment by sampila** [comment]
Hi @jilieryuyi,

Do you want to create document with bullet and numbering or extract texts from that document?

Best regards,
Alip

**Comment by jilieryuyi** [comment]
> Hi @jilieryuyi,
> 
> Do you want to create document with bullet and numbering or extract texts from that document?
> 
> Best regards, Alip

extract texts with numbering from that document

**Comment by sampila** [comment]
Hi @jilieryuyi,

Thank you for reporting the issue, we opened new issue regarding as it is different from current issue.
This one is on how to create bullet and numbering on document.

Best regards,
Alip
