### ISSUE TITLE
panic: Post "https://cloud.unidoc.io/api/metered/status"

### ISSUE THREAD

**Issue by gx19910403** [unidoc/unioffice-examples#32]
panic: Post "https://cloud.unidoc.io/api/metered/status": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
<img width="398" alt="image" src="https://github.com/unidoc/unioffice-examples/assets/49666794/1e803772-1324-4c25-a687-4ea116e2a4f7">

**Comment by sampila** [comment]
Hi @gx19910403m,

Could you share more detail regarding the issue?

It would be great if you could share code and information how to reproduce the issue.

Best regards,
Alip

**Comment by sampila** [comment]
Likely you are missing the api key to run UniOffice.

Here's example to load the License API key for UniOffice https://github.com/unidoc/unioffice-examples/blob/master/license/metered/main.go

You can re-open the issue if that still not solve your issue.

Best regards
